### ISSUE TITLE
"Time Zone" popover is shown only the left portion in the first click

### ISSUE THREAD

**Issue by ryonakano** [elementary/switchboard-plug-datetime#38]
![screenshot_20180515_231506](https://user-images.githubusercontent.com/26003928/40062694-c2cc45ca-5896-11e8-8a47-b02eeb1d28a1.png)

Whenever we launch System Settings, open "Date & Time", and click the pane which was located next to "Time Zone", the pane opens only the left portion of the popover.

![screenshot_20180515_232658](https://user-images.githubusercontent.com/26003928/40063084-7e0915ac-5897-11e8-9dfd-40e1eea92bbb.png)

If we click the pane again, this behaves as we expected. However, once we exit System Settings, this issue happens again.

On Loki & Juno

**Comment by getsnoopy** [comment]
I think this might be a remnant of a now-unavailable setting. "Etc" and "UTC" are not available as far as I can tell, so it's having trouble showing that when it's not an available option to populate. Setting it to an available option should fix the issue.

**Comment by ryonakano** [comment]
I'm still facing this issue with the new design without popover:

![Screenshot from 2021-02-23 13-54-04](https://user-images.githubusercontent.com/26003928/108803703-ab2d6300-75de-11eb-9705-de63f24b6705.png)

However, interestingly it does not happen when I launch System Settings when setting `LANG=C`:

![Screenshot from 2021-02-23 13-54-17](https://user-images.githubusercontent.com/26003928/108803706-ac5e9000-75de-11eb-83c5-1f1dad2d7426.png)
